### ISSUE TITLE
Copying Unicode text from Beat and Pasting into Microsoft Word doesn't work

### ISSUE THREAD

**Issue by venkatgoud** [lmparppei/Beat#149]
Using 1.998.9, Build 133317, Mac OS BigSur

Copy unicode text such as హీరో హీరోయిన్ from Beat into Word doesn't paste the unicode text. Instead we see strange characters.

However if I open the same fountain file in other editors such as Sublime or Highland2, then the copy paste works fine.

**Comment by lmparppei** [comment]
Does this build have any effect on the issue? Beat now stores a plain-text version of the attributed text as well.

https://www.dropbox.com/s/p4azp3na9ub596v/Beat%201.999.1.dmg?dl=1

**Comment by venkatgoud** [comment]
Nope. Same issue. I have tried both "Paste" and "Paste Special".

**Comment by lmparppei** [comment]
Some updates on this:

It seems like Word for macOS very much dislikes unicode in attributed strings and doesn't check all pasteboard items when pasting. Even pasting plain text from a PDF with Nordic alphabets (åäö) results in character set conversion problems. Because copy-pasting to any other app works, I'd rule this as a Word bug. Interestingly, it *doesn't* happen on Office 2019 when copy-pasting from Beat, but *does* with the same text copied from PDF, while Office 365 fails on both. 🫠

You can use an intermediate plain-text editor (like Apple Notes, or any text editor) to import unicode content when needed for now.
