### ISSUE TITLE
[Feature Request] Watermarked PDF generator

### ISSUE THREAD

**Issue by harp37** [lmparppei/Beat#57]
A feature that I think is sorely missing in most screenwriting software, be it your Final Drafts and Highlands, is a watermarked PDF generator that's as easy to use as a... hammer. The ability to save watermarked PDFs is critical to sharing scripts with cast and crew, especially in the age of [anonymous script leaking](https://www.republicworld.com/entertainment-news/web-series/wandavision-script-leak-everything-we-know-so-far-about-episode-6-script-leak-and-spoiler.html) and [sushi burritos](http://www.eatinglv.com/2016/06/sushi-burritos-are-a-bad-joke/).

I think it should be built-in, perhaps within the Export menu, instead of having resort to using another application, Adobe Acrobatics -- or whatever it's called -- which costs money each month that could be spending on [coffee](https://volcanicacoffee.com/products/free-range-kopi-luwak-coffee?variant=31487528370234&utm_source=bing&utm_medium=cpc&utm_campaign=**LP%20Shop%20-%20Estate%20Coffee&utm_term=4575548923532391&utm_content=118%20%7C%20Kopi%20Luwak%20Coffee%2016%20oz%20-%20Free%20Range%20Kopi%20Luwak%20%7C%20%24449.99). 

The one application that does this already, Trelby, has sadly passed away on October 11, 2016 due to a terribly outdated framework and a total lack of interest in making it suck less. Code can be found [here](https://github.com/oskusalerma/trelby/blob/master/src/watermarkdlg.py).

**Comment by lmparppei** [comment]
This wouldn't be too difficult to implement, but would add to the complexity of PDF export, which is already quite convoluted. It's also something I (and most people) would never use, so maintaining & bug fixing it would be too big of a hassle. I recommend searching for other alternatives to watermark the PDF files.

Out of curiosity, what would the real-world use case for this be? To really prevent leaks you'd probably have to watermark every single version of the screenplay and have the pages laid out as images rather than text, so that the watermark layer couldn't be removed in a second.

**Comment by harp37** [comment]
Typically having the actor/actress/crew member's name across each page helps a lot from people leaking it. I think having each page be an image would definitely help but isn't necessary. I don't really know how many people would know how to easily, or take the time to, remove the watermark.

**Comment by lmparppei** [comment]
I'd say this is not something I want to have in Beat. Watermarking screenplays with crew member names would need a batch operation anyway. And if somebody is making a series/film which has to care about leaks, it's not the screenwriter's job to provide watermarked version, as the production SHOULD have a person to handle this sort of stuff. :-)

Also, the header text can be set to contain some additional version info on every page while exporting.
