### ISSUE TITLE
Auto-capitalized lines stay capitalized after undo

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#60]
It seems that the undo feature doesn't always undo things correctly if they were auto-capitalized.

Case in point: If you were to write that `the hero dashes down the stairs, through the hallway, making his way out to:` (that is, ending with a colon) Beat will assume I was writing the world longest transition and immediately make it right-flushed and capitalized.
However, selecting UNDO at this point will only undo the right flush. The sentence will still be all caps, and any further undo will remove the text. My only choice now is to enter the action line from scratch again...

**Comment by lmparppei** [comment]
At least partially fixed in `1.89.8`. The TO: part now has to be uppercase.

**Comment by lmparppei** [comment]
**Update & note to self:**

The solution for this bug is partly figured out in `headingDidBecomeAction` delegate method in `Document` class. However, that method might be buggy, too, when it comes to undoing the changes.

Capitalizing transitions is done only for the text in `NSTextStorage`, so the parsed lines themselves still keep the original content intact. Undoing capitalization has to be handled by replacing the range storage with the string stored in line object, before the text view undoes anything.

It's a convoluted scheme, and figuring out how to hook into the undo/redo pattern is somewhat complicated. I've done some undoing hacks for when text is forward-erased (del) on a scene heading line, causing next line contents to become uppercase. I should make a general method for all of the capitalization events.

**Comment by ftolsson** [comment]
A question (as always not knowing the inner workings of your code)...:
if I'm understanding it right that you're styling the text with css for both the print and edit window -- do you need to actually capitalize scene headings (and transitions, which has a similar problem) at all? Could you instead just style headings and transitions with `text-transform: uppercase` and never have to undo capitalization at all (it just automatically reverts when the line becomes something else.)

Would that break fountain standards, i.e. must headings be written in caps to be proper legal headings?

Just an outsider's thought.

**Comment by lmparppei** [comment]
Edit window doesn't have CSS styling, it's fully native Cocoa/AppKit stuff. HTML and CSS are used for the preview and printing. I've looked into subclassing `NSTextStorage` and `NSLayoutManager` to hack `NSTextView` to show uppercase when needed, while still keeping the text itself intact, but it appears to be *very* complicated. 

Fountain definition requires certain things to be uppercase, but the correct formatting can easily be built when saving the plain text file.

**Comment by ftolsson** [comment]
On the topic of auto-capitalization, just wanted also to add (unless that should be its own issue) that forced scene headings will be automatically **bolded** but not UPPERCASED. That looks like a little oversight to me.
